version: "3.8"

services:
  public_resolver:
    container_name: 'public_resolver'
    build:
      context: ./reseau_externe/resolver
      dockerfile: Dockerfile
    expose:
      - 53/udp
      - 53/tcp

  public_web:
    container_name: 'public_web'
    build:
      context: ./reseau_externe/web
      dockerfile: Dockerfile
    expose:
      - 80
      - 443

  interne_resolver:
    container_name: 'interne_resolver'
    build:
      context: ./reseau_interne/resolver
      dockerfile: Dockerfile
    expose:
      - 53/udp
      - 53/tcp
    networks:
      secure_zone:
        ipv4_address: 192.168.0.1

  interne_web:
    container_name: 'interne_web'
    build:
      context: ./reseau_interne/web
      dockerfile: Dockerfile
    depends_on:
      - interne_db
    expose:
      - 80
      - 443
    networks:
      secure_zone:
        ipv4_address: 192.168.0.2

  interne_db:
    container_name: 'interne_db'
    build:
      context: ./reseau_interne/db
      dockerfile: Dockerfile
    volumes:
      - db-data:/var/lib/mysql
    expose:
      - 3306
    ports:
      - 3306:3306
    networks:
      secure_zone:
        ipv4_address: 192.168.0.3

  interne_mail:
    container_name: 'interne_mail'
    build:
      context: ./reseau_interne/mail
      dockerfile: Dockerfile
    expose:
      - 25
      - 143
      - 587
      - 993
    networks:
      secure_zone:
        ipv4_address: 192.168.0.4

  client_1:
    container_name: 'client_1'
    build:
      context: ./reseau_interne/client_1
      dockerfile: Dockerfile
    networks:
      secure_zone:
        ipv4_address: 192.168.0.200

  client_2:
    container_name: 'client_2'
    build:
      context: ./reseau_interne/client_2
      dockerfile: Dockerfile
    networks:
      secure_zone:
        ipv4_address: 192.168.0.201

volumes:
  db-data:

networks:
  secure_zone:
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/16
          gateway: 192.168.254.254
