version: "3.8"
services:
  web:
    container_name: externe_web
    build:
      context: .
      dockerfile: web/Dockerfile
    ports:
      - "80:80"

  public_resolver:
    image: ubuntu/bind9
    ports:
      - 53:53/udp
      - 53:53/tcp
    volumes:
      - /resolver/named.conf:/etc/bind/named.conf
      - /resolver/m2-5.ephec-ti.be.zone:/etc/bind/m2-5.ephec-ti.be.zone
      - /resolver/m2-5.ephec-ti.be.reverse:/etc/bind/m2-5.ephec-ti.be.reverse
    command: named -g
    container_name: public_resolver