version: "3.8"
services:
  web:
    container_name: externe_web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      #- "8080:8080"
  #   links:
  #     - db:db

  # db:
  #   container_name: 'db'
  #   build: ./db
  #   volumes:
  #     - db-data:/var/lib/mysql
  #   expose:
  #     - 3306
  #   networks:
  #     secure_zone:
  #       ipv4_address: 192.168.0.3